### ISSUE TITLE
`vscode-test` can't install the pre-release version of extension dep `ms-python.vscode-python-envs`

### ISSUE THREAD

**Issue by jjjermiah** [microsoft/vscode-python-environments#91]
```json
  "extensionDependencies": [
    "ms-python.vscode-python-envs"
  ],
```

in package.json

and running:

```console
❯ yarn run vscode-test                                                                  
✔ Validated version: 1.96.0
✔ Found existing install in ~/pixi-vscode2/.vscode-test/vscode-darwin-arm64-1.96.0
Error: Failed to install extensions (ms-python.vscode-python-envs): Installing extensions...
Installing extension 'ms-python.vscode-python-envs'...
Error while installing extension ms-python.vscode-python-envs: Can't install release version of 'Python Environments' extension because it has no release version.
Failed Installing Extensions: ms-python.vscode-python-envs

    at ChildProcess.<anonymous> (file:///~/pixi-vscode2/node_modules/@vscode/test-cli/out/cli/platform/desktop.mjs:134:28)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:524:28)
    at Pipe.<anonymous> (node:net:350:12)
```

tried:

```console
❯ yarn run vscode-test --install-extension "ms-python.vscode-python-envs" --pre-release 
✔ Validated version: 1.96.0
✔ Found existing install in ~/pixi-vscode2/.vscode-test/vscode-darwin-arm64-1.96.0
Error: Failed to install extensions (ms-python.vscode-python-envs): Installing extensions...
Installing extension 'ms-python.vscode-python-envs'...
Error while installing extension ms-python.vscode-python-envs: Can't install release version of 'Python Environments' extension because it has no release version.
Failed Installing Extensions: ms-python.vscode-python-envs

    at ChildProcess.<anonymous> (file:///~/pixi-vscode2/node_modules/@vscode/test-cli/out/cli/platform/desktop.mjs:134:28)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:524:28)
    at Pipe.<anonymous> (node:net:350:12)
```

Is there a work-around for this?

**Comment by karthiknadig** [comment]
I think the recommendation was to do this in code:
```
import { runVSCodeCommand} from '@vscode/test-electron';
```
Something like this:
```
await runVSCodeCommand(['--install-extension', 'ms-python.vscode-python-envs'], { version: 'insiders' });

```

You will need `@vscode\test-electron` version `2.4.1`  to get `runVSCodeCommand`

**Comment by karthiknadig** [comment]
@jjjermiah For CLI it looks like you can use `extension@version` to a particular version. This seems to be a limitation of the `vscode-test` CLI.

**Comment by jjjermiah** [comment]
Just tried the CLI solution and it worked like a charm! Thank you.
